Add support for object polymorhism in HOCON decoder
Kotlin/kotlinx.serialization pull request #1136
Opened 2020-10-12 12:28 UTC by shanshin

2020-10-12 19:42 UTC, sandwwraith requested changes

2020-10-12 19:42 UTC, sandwwraith commented on formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt
> +            val config: Config = if (currentTagOrNull != null) conf.getConfig(currentTag) else conf;
```suggestion
            val config = if (currentTagOrNull != null) conf.getConfig(currentTag) else conf
```

2020-10-12 19:42 UTC, sandwwraith commented on formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt
> +            val discriminator = classDiscriminator
Redundant variable?

2020-10-12 19:42 UTC, sandwwraith commented on formats/hocon/src/main/kotlin/kotlinx/serialization/hocon/Hocon.kt
> +     * This is an option for legacy HOCON format and should not be generally used.
Not sure if 'the legacy HOCON format' words are applicable here — HOCON never had polymorphism in the first place, so array-based is a legacy only for JSON. I think we can stick with the words 'legacy polymorphism format'

2020-10-12 19:42 UTC, sandwwraith commented on formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconPolymorphismTest.kt
> +import kotlinx.serialization.SerialName
We usually enable star imports in Editor-Code Style-Kotlin because they're almost every time from one of the library's packages

2020-10-21 17:16 UTC, sandwwraith approved these changes

2020-10-21 17:59 UTC, sandwwraith commented
@shanshin please rebase your changes to resolve conflicts

2020-10-21 18:18 UTC, shanshin commented
> @shanshin please rebase your changes to resolve conflicts

ready

2020-10-22 12:27 UTC, merged