Prepare 1.1.0-RC
Kotlin/kotlinx.serialization pull request #1316
Opened 2021-02-01 16:40 UTC by sandwwraith

2021-02-02 15:09 UTC, qwwdfsad approved these changes
👍

2021-02-02 15:09 UTC, qwwdfsad commented on CHANGELOG.md
> +  * Add serializerOrNull function for KType and Type arguments (#1164)
Here and below I suggest wrapping all methods/classes into backticks, so they are properly rendered

2021-02-03 01:16 UTC, Him188 requested changes

2021-02-03 01:16 UTC, Him188 commented on CHANGELOG.md
> +This feature requires Kotlin compiler 1.4.30-RC and enabling new IR compilers for for [JS](https://kotlinlang.org/docs/reference/js-ir-compiler.html) and [JVM](https://kotlinlang.org/docs/reference/w
Maybe duplicated 'for'?
```suggestion
This feature requires Kotlin compiler 1.4.30-RC and enabling new IR compilers for [JS](https://kotlinlang.org/docs/reference/js-ir-compiler.html) and [JVM](https://kotlinlang.org/docs/reference/whatsnew14.html#new-jvm-ir-backend).
```

2021-02-03 13:41 UTC, sandwwraith commented on CHANGELOG.md
> +This feature requires Kotlin compiler 1.4.30-RC and enabling new IR compilers for for [JS](https://kotlinlang.org/docs/reference/js-ir-compiler.html) and [JVM](https://kotlinlang.org/docs/reference/w
Indeed, thanks!

2021-02-03 16:36 UTC, Whathecode commented
The new Kotlin [already release mentions this version](https://kotlinlang.org/releases.html). :) I guess a new release is imminent! 🥳

2021-02-03 18:35 UTC, merged