dont-encode-nulls
Kotlin/kotlinx.serialization pull request #1376
Opened 2021-03-17 04:05 UTC by Vacxe

Allow to exclude object from encoded string if it's `null`

`encodeNulls` by default `true` to support backward compatibility 

See: #195

2021-03-17 12:19 UTC, qwwdfsad requested changes
With the proposed change, the most important invariant of the serialization framework is violated: now we cannot deserialize back what we've just serialized.

The issue, unfortunately, is more complex than that and that's why it's not yet addressed. We are not ready to accept this PR and break our own invariant

2021-03-17 12:19 UTC, closed without merging

2021-03-17 22:59 UTC, Vacxe commented
@qwwdfsad thank for quick reply. You have a reasonable arguments to close this PR however:

* We have about 2-3 additional major libraries for serialization such as Gson and Moshi which also popular for usage. [All of them provide different strategies for serialization](https://github.com/Vacxe/json-parsers-branchmark)

For example Moshi do not serialized nulls values

* Moshi

    * Input object: <BR>
    ```PrimitiveDataClass(name=Object 770591202, int=-822616830, double=0.8621779982333868, float=0.33106828, boolean=true, optional=null)```
    * Serialized `String` <BR>
    ```{"name":"Object 770591202","int":-822616830,"double":0.8621779982333868,"float":0.33106828,"boolean":true}}```
    * Deserialize object <BR>
    ```PrimitiveDataClass(name=Object 770591202, int=-822616830, double=0.8621779982333868, float=0.33106828, boolean=true, optional=Optional String))```
    

* From time to time serialization is used for network calls. And it can affect some client-server logic due migration from one library to this one.

* This feature under configuration flag and can be enabled if it's required.

* Removing null values (if client-server contract accepting this) can significantly reduce network call weight.

* Anyway, this is not a main strategy for serialization and can be applied if required.

---

I honestly understanding your path of light but in real world we have to many casts of shadows. 


Anyway I respecting your decision

2021-03-18 09:45 UTC, qwwdfsad commented
Thanks for your input! Your concerns are indeed valid, we are going to address this issue right after the next release (including deserialization of such data back as well)

2021-03-18 12:17 UTC, Vacxe commented
@qwwdfsad Cheers. Look forward to solving this problem.