Add polymorphic default serializers (as opposed to deserializers)
Kotlin/kotlinx.serialization pull request #1686
Opened 2021-09-18 14:01 UTC by Earthcomputer

Closes #1317. Possible usecases for this are described in that issue.

- Adds the concept of polymorphic default serializers, and renames the existing concept of default serializers to default deserializers to avoid confusion.
- Deprecates functions that refer to polymorphic default deserializers as simply "default", in favour of new functions with more explicit names.

I am by no means a kotlin expert so please let me know if there's something that needs changing.

2021-11-11 11:41 UTC, sandwwraith requested changes
Please address my last comment (https://github.com/Kotlin/kotlinx.serialization/pull/1686#discussion_r732866361)

2021-11-11 20:52 UTC, Earthcomputer commented on core/commonMain/src/kotlinx/serialization/modules/PolymorphicModuleBuilder.kt
> +    public fun <T : Base> defaultSerializer(defaultSerializerProvider: (value: T) -> SerializationStrategy<T>?) {
Hi, sorry I read your comment and then got sidetracked and forgot about it. I agree, 4 is the best solution

2021-11-11 23:40 UTC, Earthcomputer commented
Done :+1:

2021-11-12 13:12 UTC, sandwwraith reviewed
Great work! I think it's ready when you fix minor comments

2021-11-12 19:38 UTC, Earthcomputer commented
Done

2021-11-22 15:37 UTC, sandwwraith approved these changes
Thanks again!

2021-11-22 15:37 UTC, merged