Remove @ExperimentalSerializationApi from base serial format interfaces
Kotlin/kotlinx.serialization pull request #1688
Opened 2021-09-21 13:33 UTC by sandwwraith

because they are unstable for inheritance only, and experimentality is now leaking in function signatures

Fixes #1668

2021-09-21 13:36 UTC, sandwwraith commented
We also may need to revisit experimental annotation on `SerialDescriptor` members (AFAIR, it was for inheritance too).

Also, `JsonConfiguration` looks like it may be stable already.

2021-09-21 15:23 UTC, qwwdfsad requested changes
Please add a comment that these interfaces are experimental for implementation

2021-09-21 17:01 UTC, sandwwraith commented
It's been there all along: https://github.com/Kotlin/kotlinx.serialization/blob/82134bd7cbca9da53ce2f73bd0047b96c76e47db/core/commonMain/src/kotlinx/serialization/SerialFormat.kt#L22

2021-09-21 20:08 UTC, BenWoodworth commented
I don't think it's necessary (documenting that 3rd-party formats aren't stable seems like enough), just something I've been pondering the past week. But conceivably something like this could be used if you still want the implementing classes to explicitly opt in, bringing the instability front-and-center to the format dev:

```kotlin
interface SerialFormat {
    @ExperimentalSerializationApi
    @Suppress("PropertyName")
    @Deprecated(
        "SerialFormat interface is not stable for inheritance in 3rd party libraries, " +
                "as new methods might be added to this interface or contracts of the existing methods can be changed.",
        level = DeprecationLevel.HIDDEN,
    )
    val SerialFormat_interface_is_not_stable_for_inheritance: Unit // or maybe Nothing

    // ...
}

class ThirdPartySerialFormat : SerialFormat {
    @ExperimentalSerializationApi
    override val SerialFormat_interface_is_not_stable_for_inheritance: Unit = Unit
}
```

I don't think this would be a breaking change with existing 3rd party formats at runtime (e.g. no `NoSuchMethodError` since the property can never be accessed), but you would of course need to add the override in when compiling against kxs 1.3.0.

2021-09-22 15:27 UTC, qwwdfsad approved these changes

2021-09-22 15:56 UTC, sandwwraith commented
@BenWoodworth Idea is good, and I think it was used in other parts somewhere (or in kotlinx.coroutines), but It looks like an overkill for this task. Interfaces are small, and usually inherited by format authors who read the documentation and know what's what

2021-09-22 15:56 UTC, merged

2021-09-22 18:49 UTC, BenWoodworth commented
Hah I figured. Cool to know it's been used elsewhere, and glad to see this merged! :)