Alow Kotlin's null literal in JSON DSL
Kotlin/kotlinx.serialization pull request #1907
Opened 2022-04-20 03:39 UTC by Lukellmann

Right now you can not really use Kotlin's `null` literal with the JSON DSL:
```kotlin
val obj = buildJsonObject {
    put("string", "string")
    put("boolean", true)
    put("number", 1)

    // Error: Overload resolution ambiguity. All these functions match.
    // - public fun JsonObjectBuilder.put(key: String, value: Boolean?): JsonElement? defined in kotlinx.serialization.json
    // - public fun JsonObjectBuilder.put(key: String, value: Number?): JsonElement? defined in kotlinx.serialization.json
    // - public fun JsonObjectBuilder.put(key: String, value: String?): JsonElement? defined in kotlinx.serialization.json
    put("null", null)
}

val arr = buildJsonArray {
    add("string")
    add(true)
    add(1)

    // Error: Overload resolution ambiguity. All these functions match.
    // - public fun JsonArrayBuilder.add(value: Boolean?): Boolean defined in kotlinx.serialization.json
    // - public fun JsonArrayBuilder.add(value: Number?): Boolean defined in kotlinx.serialization.json
    // - public fun JsonArrayBuilder.add(value: String?): Boolean defined in kotlinx.serialization.json
    add(null)
}

val p0 = JsonPrimitive("string")
val p1 = JsonPrimitive(true)
val p2 = JsonPrimitive(1)

// Error: Overload resolution ambiguity. All these functions match.
// - public fun JsonPrimitive(value: Boolean?): JsonPrimitive defined in kotlinx.serialization.json
// - public fun JsonPrimitive(value: Number?): JsonPrimitive defined in kotlinx.serialization.json
// - public fun JsonPrimitive(value: String?): JsonPrimitive defined in kotlinx.serialization.json
val p3 = JsonPrimitive(null)
```
All of these errors could be resolved by using a cast like `null as String?` or by using `JsonNull` directly.
However, this is somewhat irritating as other primitives that are supported by JSON (numbers, strings, `true` and `false`) can be used directly while `null` can't.

To resolve the overload resolution ambiguity and allow use of the `null` literal in the JSON DSL, this PR adds overloads for the `JsonObjectBuilder.put()`, `JsonArrayBuilder.add()` and `JsonPrimitve()` functions that take an argument of type `Nothing?`.

2022-04-20 03:46 UTC, Lukellmann commented
I haven't added `@ExperimentalSerializationApi` to the new functions yet, but I'm supposed to do this, right?

2022-05-26 23:01 UTC, Lukellmann commented
> I haven't added `@ExperimentalSerializationApi` to the new functions yet, but I'm supposed to do this, right?

I added the annotations now.

2022-06-02 16:39 UTC, sandwwraith requested changes
Sorry for the long delay, your PR slipped out of my attention. You were completely right with `@ExperimentalSerializationApi`. I think we can merge this after you address the comments

2022-06-02 20:41 UTC, Lukellmann commented on formats/json/commonMain/src/kotlinx/serialization/json/JsonElement.kt
> +/** Returns [JsonNull]. */
It's not strictly needed, but it feels more consistent to me.
But it's fine for me if you think this one is unnecessary and should be removed.

2022-06-02 20:52 UTC, Lukellmann commented on formats/json/commonMain/src/kotlinx/serialization/json/JsonElement.kt
> -    public override val isString: Boolean
Wasn't aware of this, I just saw the warnings in my IDE 👍

2022-06-03 14:01 UTC, sandwwraith commented on formats/json/commonMain/src/kotlinx/serialization/json/JsonElement.kt
> +/** Returns [JsonNull]. */
Well, maybe it would be easier to discover. Then it's better to use doc style as in the other functions:

```
/**
* Creates [JsonNull]
*/
```

2022-06-03 23:44 UTC, Lukellmann commented on formats/json/commonMain/src/kotlinx/serialization/json/JsonElement.kt
> +/** Returns [JsonNull]. */
I adjusted the doc style 👍

2022-06-07 15:55 UTC, sandwwraith approved these changes

2022-06-07 15:56 UTC, merged

2022-06-07 15:56 UTC, sandwwraith commented
Thank you for your efforts!