Get rid of @ExperimentalUnsignedTypes on our declarations that levera…
Kotlin/kotlinx.serialization pull request #1962
Opened 2022-06-03 14:49 UTC by qwwdfsad

…ge non-experimental unsigned types

2022-06-03 16:43 UTC, sandwwraith commented
I think we can remove experimentality, I don't remember any problems with them

2022-06-03 17:20 UTC, qwwdfsad commented
I'll do it in a separate PR then

2022-06-07 16:17 UTC, sandwwraith requested changes
We also need to change a bit of documentation here: https://github.com/Kotlin/kotlinx.serialization/blob/8be6845927414a844ffebedc871dd8bc0d4b8aee/docs/builtin-classes.md#L71

2022-06-07 16:17 UTC, sandwwraith commented on formats/json/commonMain/src/kotlinx/serialization/json/internal/StreamingJsonDecoder.kt
> +@OptIn(ExperimentalSerializationApi::class)
You've missed `StreamingJsonEncoder`

2022-06-15 18:37 UTC, sandwwraith approved these changes

2022-06-24 14:43 UTC, merged