Support Serializer for Nothing on the JS target
Kotlin/kotlinx.serialization pull request #2330
Opened 2023-06-12 10:15 UTC by ShreckYe

Resolves #932 (the JS target part)

2023-07-11 14:15 UTC, sandwwraith requested changes
Hi! Thanks for the PR. Given that Kotlin ticket likely won't be fixed soon, it is OK to add this workaround after fixing minor issues.

2023-07-11 14:15 UTC, sandwwraith commented on formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/ProtobufNothingTest.kt
> +    /*private*/ data class NullableNothingBox(val value: Nothing?) // `private` doesn't work on the JS legacy target
It's OK to leave nested test classes as public

2023-07-12 06:04 UTC, ShreckYe commented
@sandwwraith Hi I have updated the tests. Please check if they are OK now.

2023-07-12 12:56 UTC, sandwwraith approved these changes

2023-07-12 12:58 UTC, merged