Fix beginStructure in JsonTreeDecoder when inner structre descriptor is same as outer
Kotlin/kotlinx.serialization pull request #2346
Opened 2023-06-23 16:17 UTC by ionspin

Attempt 2 (previous pull request and discussion here #2344) at solving #2343. This time instead of returning the same instance of decoder (with invalid position) a new instance is created, and `polyDiscriminator` and `polyDescriptor` are passed to the new instance.

This way check for unknown keys in `endStructure` can properly filter out polymorphic discriminator (by default "type) from potential unknown keys.

Added a simple test that fails with the original code and passes with the fix, but I'm not sure what to call it or if it's in the right place.

2023-06-27 14:58 UTC, sandwwraith requested changes
Pull requests with code changes should be opened against `dev`. You have to rebase your commit on dev and then change base in the PR (just changing base results in unrelated commits added). Thank you!

2023-06-27 14:58 UTC, sandwwraith commented on formats/json-tests/commonTest/src/kotlinx/serialization/json/polymorphic/JsonTreeDecoderPolymorphicTest.kt
> +    fun testDecodingWhenClassContainsItself() {
Please use `JsonTestBase` as a base class for test and function `parametrizedTest`. It helps check behavior for all possible json decoding paths, including JsonTreeDecoder (problematic one), as well as String decoder and Stream integration. You can see example of using one here: https://github.com/Kotlin/kotlinx.serialization/blob/5e8ccad1f70a9457e0ffe6ae6b10a0bd0eaaa618/formats/json-tests/commonTest/src/kotlinx/serialization/json/JsonReifiedCollectionsTest.kt#L15

2023-06-28 17:20 UTC, sandwwraith commented on formats/json-tests/commonTest/src/kotlinx/serialization/json/polymorphic/JsonTreeDecoderPolymorphicTest.kt
> +        val decoded : Sealed = Json.decodeFromString(encoded, jsonTestingMode)
```suggestion
        val decoded: Sealed = Json.decodeFromString(encoded, jsonTestingMode)
```

formatting

2023-06-29 09:42 UTC, ionspin commented
I also squashed the commits.

2023-06-29 11:43 UTC, sandwwraith approved these changes

2023-06-29 11:44 UTC, merged

2023-06-29 11:44 UTC, sandwwraith commented
Great job, thanks!