Support preserving unknown fields in ProtoBuf format
Kotlin/kotlinx.serialization pull request #2860
Opened 2024-11-18 04:03 UTC by xiaozhikang0916

Introducing new annotation `@ProtoUnknownFields` and built-in type `ProtoMessage`, to store any fields with proto ids that are undefined in current message class.

In my understanding, both ktx-serialization and protocol buffer are designed in strong typing, all messages used in code should be well defined in kt class or proto message. Therefore I would like to keep `ProtoMessage` and `ProtoField` minimun published. Not like `JsonObject` in json format, users cannot retrieve detailed data from it.

Close #2655

2024-11-18 04:05 UTC, xiaozhikang0916 commented
@sandwwraith Hi, please take a look here?

2024-11-22 17:09 UTC, sandwwraith commented
@xiaozhikang0916 Sure, when I'll have time

2024-11-22 17:27 UTC, pdvrieze reviewed
The structure you use to represent protobuf content is somewhat complex, especially considering the protobuf wire format. You probably want to think a bit more how to represent protobuf data where the wire based information permits that. In particular you may want to distinguish primitives, "blobs", packed arrays. You may also allow users to observe a protobuf with provided metadata.

2024-11-26 06:12 UTC, xiaozhikang0916 commented
@pdvrieze Actually I don't want to decode the protobuf wire data into a tree-structure type like what `JsonObject` do, neither provide retreiving method of the content.

The raw content in protobuf wire data is quite ambiguous that, you can even not possible to tell whether a `VARINT 1` is 1 or -1 or true, or tell a `LEN` field is string or sub-message. The only way to parse wire data content correctly and explictly is to parse with message definition, or with a concrete type in kotlin.

Base on it, `ProtoMessage` here is not designed for retrieving content from undefined fields, but for holding it only.

2025-03-06 16:25 UTC, xiaozhikang0916 commented
Any progress about it? We have plan on upgrading Kotlin and serialization runtime version, and it would be great if we can have this functionality in near future.

2026-02-04 15:51 UTC, shanshin commented on docs/formats.md
> +To keep the unknown fields, add a property in type `ProtoMessage` with default value `null` or `ProtoMessage.Empty`, and annotation `@ProtoUnknownFields` to your data class.
Should we be more strict here, eg use only nullable (null if there are no unknown fields) or non-null property (ProtoMessage.Empty if there are no unknown fields)?

2026-02-04 15:51 UTC, shanshin commented on docs/formats.md
> +To keep the unknown fields, add a property in type `ProtoMessage` with default value `null` or `ProtoMessage.Empty`, and annotation `@ProtoUnknownFields` to your data class.
@sandwwraith, I have a slight fear that the name `ProtoMessage` is too general - users may think that this is a universal class with a map-like structure

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt
> +                        "Only one unknown fields holder is allowed in a message"
Should we write descriptor name here?

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt
> +                        "ProtoUnknownFields is only allowed on property with type kotlinx.serialization.protobuf.ProtoMessage, with its original serializer."
And here

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt
>                  if (index == -1) { // not found
`-1` looks more and more like a magic value now, should we create a constant for it (for example, to show that `unknownHolderIndex` is initialized with `-1` for a reason)?

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufReader.kt
> +            ProtoWireType.VARINT -> byteArrayOf(readInt(ProtoIntegerType.DEFAULT).toByte())
Is there a bug here?
Int is converted to Byte, resulting in a byte array of one element. 

It's necessary to add a test for large values of each of the specified types.

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoTypes.kt
> +public annotation class ProtoUnknownFields
We should add the compiler plugin check that this annotation is used only once in a class and only with a specific type of property (`ProtoMessage` now)

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoMessageSerializer.kt
> +        get() = "UnknownProtoFieldsHolder"
Name should contains original descriptor name

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufEncoding.kt
> +                value = data.first().toInt(),
Only first first byte is read as an Int, for numbers greater than 127, there will be an error.

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufEncoding.kt
> +                value = data.first().toLong(),
Same here

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufEncoding.kt
> +                value = data.first().toInt(),
And here

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoMessage.kt
> +internal sealed interface ProtoContentHolder {
In current implementation ProtoContentHolder is useless, `MessageContent` is not used anywhere.

It should be deleted, and `ProtoField` should only store a byte array, or indeed, there should be heirs for each type (VARINT, i64, SIZE_DELIMITED, etc), without unnecessary conversion to a byte array.

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoMessage.kt
> +    public fun asByteArray(): ByteArray =
The current implementation looks like it overload the GC, but it is not used anywhere.
I would prefer to delete it in this form.

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoMessage.kt
> +    val contentLength: Int
The size can be calculated without creating a new byte array.

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/ProtobufUnknownFieldsTest.kt
> +    @Serializable
Tests are required for all supported types of unknown fields in extreme values:
VARINT, i64, SIZE_DELIMITED, i32, for values like 0/empty message, -1, MIN_VALUE, MAX_VALUE, message with length > 65kB, etc.

2026-02-04 15:51 UTC, shanshin commented on formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/ProtobufUnknownFieldsTest.kt
> +        val encoded = "082a120234321a032a2a2a202a202a202a2a120a023432102a1a0234321a0234321a023432"
I would suggest building the main tests not around the hardcoded HEX values, but according to the following rule: everything that is encoded must be decoded in exactly the same form.

Steps:
- first encode what is
- then decode it to type with `ProtoUnknownFields`
- compare known fields
- encode the type with `ProtoUnknownFields` 
- this value must match the first encoded one

This is almost the same approach, but it will reduce the use of magic constants in all tests.

Of course, it is possible to check decoding from a constant HEX value, but one test will be enough for this.

2026-02-06 07:52 UTC, xiaozhikang0916 commented on docs/formats.md
> +To keep the unknown fields, add a property in type `ProtoMessage` with default value `null` or `ProtoMessage.Empty`, and annotation `@ProtoUnknownFields` to your data class.
You are right. `ProtoMessage` was introduced as general data container for ProtoBuf format for convenience of decoding/encoding and writing test code. All its read/write apis are kept internal to avoid creating universal map-like structure of proto. But it is too complex to rewrite the decoding/encoding logic with this type. I renamed this type and removed its unused fields.

2026-02-06 07:53 UTC, xiaozhikang0916 commented on docs/formats.md
> +To keep the unknown fields, add a property in type `ProtoMessage` with default value `null` or `ProtoMessage.Empty`, and annotation `@ProtoUnknownFields` to your data class.
`ProtoContentHolder` is also removed.

2026-02-06 15:38 UTC, xiaozhikang0916 commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoTypes.kt
> +public annotation class ProtoUnknownFields
Do I need a pr in the kotlin repo?

2026-02-23 11:28 UTC, shanshin commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoTypes.kt
> +public annotation class ProtoUnknownFields
> Do I need a pr in the kotlin repo?

That would help a lot

2026-03-18 09:44 UTC, xiaozhikang0916 commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoTypes.kt
> +public annotation class ProtoUnknownFields
A pr in kotlin repo: https://github.com/JetBrains/kotlin/pull/5755

2026-03-20 18:47 UTC, shanshin commented
LGTM, but I think @sandwwraith  should also take a cursory look to check the style and documentation.

2026-05-07 14:19 UTC, sandwwraith commented
Did we discuss an overall design for the feature? I have three questions:

1. If we support only `ProtoUnknownFieldHolder` type, the annotation seems unnecessary. We have full access to the descriptor everywhere, so we can simply check descriptor/serialName for equality.

2. Do we want to support only this type? It is typical to store unknown fields only in `ByteArray` — in case we are not interested in them at all, but want to preserve them when we'll serialize the message again later. Why choose a separate type? Especially given that `ProtoField` is internal, there's no way to access at least protonumbers of new fields (in case you want to, e.g., log or dump them).  `ProtoUnknownFieldHolder` probably makes more sense when ProtoField is public. But ProtoField contains a ByteArray anyway, so we're back to square one. 
3. Maybe we need functionality to parse a raw ByteArray to raw unknown fields? Then we can get in the cycle ProtoUnknownFieldHolder - ProtoField - ByteArray - inner message as ProtoUnknownFieldHolder - ProtoField - ....

2026-05-09 15:05 UTC, xiaozhikang0916 commented
Hi @sandwwraith 

In my point of view, a byte array means nothing without a proto message (or class) definition, and unknown proto fields should be a format specific feature in ProtoBuf format, which should not be serialized to other format like Json. So I avoid exposing raw ByteArray field to developers, but introducing a seperate type `ProtoUnknownFieldHolder` with custom serializer to keep it internal to ProtoBuf only.

> Maybe we need functionality to parse a raw ByteArray to raw unknown fields?

In fact, I tried to write a `JsonElement` equivalent in my very first implementation, but soon I realized that it required a full rewrite of proto decoder. To keep this branch focused on one feature, I just simply wrap a ByteArray in the new `ProtoUnknownFieldHolder` type. And I am happy to see (or contribute to) the feature paring byte array to arbitrary `ProtoElement` type comes true.

To sum up, `ProtoUnknownFieldHolder` as a simple wrapper of `ByteArray` is necessary. It can be renamed to `ProtoElement` in the future if this feature is accepted, and an annotation will be necessary to mark which field should be used as the holder.

2026-05-11 12:43 UTC, sandwwraith commented
> and unknown proto fields should be a format specific feature in ProtoBuf format, which should not be serialized to other format like Json.

I imagine it is possible to transform a Kotlin's class decoded from protobuf to Json and then add something like `"unknownFields": 0xab341....`, although I do not know if there is any use case to do so. Maybe if you're writing some kind of protobuf-to-human-readable translator.

> To sum up, ProtoUnknownFieldHolder as a simple wrapper of ByteArray is necessary

In that case, is there a need for `ProtoField`? I think we can make it even more simple without it.

So, if you want to keep separate `ProtoUnknownFieldHolder`:
- Let's get rid of the annotation
- Don't try to parse inner structure to ProtoField

2026-05-18 14:39 UTC, xiaozhikang0916 commented
I have tried 2 ways to improve it, but both of them have some limitations.

- A raw `ByteArray` field with annotation
  - It brings a raw `ByteArray` field to the data class, so the compiler will warn that you should  override `equals()` and `hashCode()` manually, and it brings extremely extra effort to devs.
- `ProtoUnknownFieldHolder` field without annotation
  - The proto decoder reads all infomation of elements from their annotations, and there is no class/type info in the `SerialDescriptor`, so I will need many instance comparation of `ProtoUnknownFieldHolder.serializer` here.  Please tell me if I missed anything.
  - An alternate way is injecting this annotation from compiler plugin, but it will bring more complexity to this feature.

Do you have any suggestion? @sandwwraith

2026-05-20 10:02 UTC, sandwwraith commented
> It brings a raw ByteArray field to the data class, so the compiler will warn that you should override equals() and hashCode() manually, and it brings extremely extra effort to devs.

Good point, I agree that ByteArray is not optimal in this case.

> The proto decoder reads all infomation of elements from their annotations, and there is no class/type info in the SerialDescriptor

There's `serialName,` which is usually sufficient for this kind of check. Or you can simply do `desciptor == ProtoUnknownFieldsSerializer.descriptor` as SerialDescriptors support equality, particularly for this purpose.

2026-06-08 05:29 UTC, xiaozhikang0916 commented
Do we need any further more changes here? @sandwwraith

2026-06-23 15:23 UTC, sandwwraith requested changes

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/Helpers.kt
> +internal const val INDEX_NOT_EXISTSED = -1
Typo, should be EXISTED

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt
> +                        "Only one unknown fields holder is allowed in a message, but get ${descriptor.getElementName(i)} and ${descriptor.getElementName(unknownHolderIndex)}"
```suggestion
                        "Only one unknown fields holder is allowed in a message, but two properties have ProtoUnknownFieldHolder type: ${descriptor.getElementName(i)} and ${descriptor.getElementName(unknownHolderIndex)}"
```

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt
> +            deserializer == ProtoUnknownFieldHolderSerializer -> {
You should compare `deserializer.descriptor == ProtoUnknownFieldHolderSerializer.descriptor` — see how it is done with `deserializeByteArray` above

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufEncoding.kt
> +        serializer == ProtoUnknownFieldHolderSerializer -> {
Same here

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +    return ByteArray(0)
I think it's better to fail with ClassCastException to ProtobufDecoder rather than silently return wrong data

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +internal class UnknownFieldsDescriptor(private val original: SerialDescriptor) : SerialDescriptor by original {
I don't see the point of making a wrapper class if the only instance will be in `ProtoUnknownFieldHolderSerializer`

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +    override val descriptor: SerialDescriptor
You don't really need to create new descriptor every time via `get()`. You can use a specialized [delegate descriptor constructor](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization.descriptors/-serial-descriptor.html): `override val descriptor: SerialDescriptor = SerialDescriptor("kotlinx.serialization.protobuf.ProtoUnknownFieldHolder", ByteArraySerializer().descriptor)`

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoUnknownFieldHolder.kt
> + * Especially used as a holder of unknown proto fields in an arbitrary protobuf message.
Since representing unknown fields is its only usage, we should rephrase this. Maybe

`Represents a thin wrapper over fields in a protobuf message. Used to store unknown proto fields.`

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoUnknownFieldHolder.kt
> +    internal val fields: ByteArray
Should we make it public? At least priniting them is probably a popular request. One may also want to try to edit them before writing back

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoUnknownFieldHolder.kt
> +    override fun equals(other: Any?): Boolean {
`toString()` is missing

2026-06-23 15:23 UTC, sandwwraith commented on formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/ProtobufUnknownFieldsTest.kt
> +        assertUnknownFieldRoundTrip(FloatData(1, Float.MIN_VALUE), FloatData.serializer())
This test fails on JS, probably due to a difference in precision. Can you investigate whether it is safe to ignore this failure?

2026-06-23 15:24 UTC, sandwwraith commented on formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/ProtobufUnknownFieldsTest.kt
> +        assertUnknownFieldRoundTrip(FloatData(1, Float.MIN_VALUE), FloatData.serializer())
`Expected <FloatData(id=1, value=1.4e-45)>, actual <FloatData(id=1, value=1.401298464324817e-45)>`

2026-06-25 16:13 UTC, xiaozhikang0916 commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt
> +            deserializer == ProtoUnknownFieldHolderSerializer -> {
Changed, but can you elaborate why this pattern is recommended here?

2026-06-25 16:15 UTC, xiaozhikang0916 commented on formats/protobuf/commonTest/src/kotlinx/serialization/protobuf/ProtobufUnknownFieldsTest.kt
> +        assertUnknownFieldRoundTrip(FloatData(1, Float.MIN_VALUE), FloatData.serializer())
I believe it is save to ignore this failure here. Json and Cbor only test float value in jvm target because of this precision issue.

2026-06-25 16:20 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtobufDecoding.kt
> +            deserializer == ProtoUnknownFieldHolderSerializer -> {
We do not require any equality contract from serializers, and keep the instantiation strategy an implementation detail. Changing `object` to `class` and vice versa may break the serializer's identity, while `SerialDescriptor.equals` is well-defined.

2026-06-25 16:23 UTC, xiaozhikang0916 commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +internal class UnknownFieldsDescriptor(private val original: SerialDescriptor) : SerialDescriptor by original {
If we check whether a deserializer is `ProtoUnknownFieldHolderSerializer` by comparing its descriptor, a wrapper is needed here to do the comparasion, otherwise, a `ByteArraySerializer` may be considered same type as `ProtoUnknownFieldHolderSerializer` in `deserializer.descriptor == ProtoUnknownFieldHolderSerializer.descriptor`.

2026-06-25 16:30 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +internal class UnknownFieldsDescriptor(private val original: SerialDescriptor) : SerialDescriptor by original {
`SerialDescriptor("kotlinx.serialization.protobuf.ProtoUnknownFieldHolder", ByteArraySerializer().descriptor)` provides such wrapper

2026-06-25 16:58 UTC, xiaozhikang0916 commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoUnknownFieldHolder.kt
> +    internal val fields: ByteArray
Sure. And I believe a list of fields data is more helpful than concating them into one byte array so that developers can know how many unknown fields is captured in this holder.

> One may also want to try to edit them before writing back

It is quite diffcult to do that in this implementation, because it is hard to know the id of these fields. To store and retrieve the id, we need a holder for arbitrary proto fields, but we just desided to remove `ProtoField` introduced in this pr.

2026-07-14 10:42 UTC, sandwwraith commented on docs/formats.md
> +To keep the unknown fields, add a property in type `ProtoUnknownFieldHolder` with default value `null` or `ProtoUnknownFieldHolder.Empty` to your data class.
```suggestion
To keep the unknown fields, add a property of type `ProtoUnknownFieldHolder` with default value `null` or `ProtoUnknownFieldHolder.Empty` to your data class.
```

2026-07-14 10:42 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoUnknownFieldHolder.kt
> +    public val fields: List<ByteArray>
I'm still not convinced we should provide any API beyond simple `public val fields: ByteArray`. Can you provide an example where the number of such fields matters, and where having a `List` would make a big difference? IMO, it is enough to know just size and raw content for some toString/debuggability, and you can't really do anything beyond that.

If we are going to add `ProtoUnknownField` in the future, it will also be easier to hide plain byte array rather than `fields+contentSize+size` altogether.

2026-07-17 03:08 UTC, xiaozhikang0916 commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoUnknownFieldHolder.kt
> +    public val fields: List<ByteArray>
Got it. Any further API for the internal fields will be suspended until a real `ProtoField` is introduced.

2026-08-17 15:38 UTC, sandwwraith requested changes

2026-08-17 15:38 UTC, sandwwraith commented on docs/formats.md
> +Kotlin Serialization `ProtoBuf` format supports preserving unknown fields, as described in the [Protocol Buffer-Unknown Fields](https://protobuf.dev/programming-guides/proto3/#unknowns).
```suggestion
Kotlin Serialization `ProtoBuf` format supports preserving unknown fields, as described in the [Protocol Buffer - Unknown Fields](https://protobuf.dev/programming-guides/proto3/#unknowns).
```

2026-08-17 15:38 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/Helpers.kt
> +    if (descriptor.getElementDescriptor(index).isUnknownFieldsDescriptor) {
Minor: KDoc for this function has to be updated as well.

Also, it looks suspiciously similar to `fun SerialDescriptor.extractParameters`. Later investigation is needed on whether we can unify them (out of scope for this PR)

2026-08-17 15:38 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +internal fun readRawFieldBytes(compositeDecoder: CompositeDecoder): ByteArray {
You can have `compositeDecoder: ProtobufDecoder` here because of smartcast. You don't need a second `is`.

2026-08-17 15:38 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +        if (decoder is ProtobufDecoder) {
Follow the pattern with `.asJsonEncoder/Decoder` (https://github.com/Kotlin/kotlinx.serialization/blob/304e858ccc7066854637d86ab80056f5f2bcc094/formats/json/commonMain/src/kotlinx/serialization/json/JsonElementSerializers.kt#L203) — perform check here, throw IllegalStateException on failure instead of CCE.

2026-08-17 15:38 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +        if (encoder is ProtobufEncoder) {
Same here — ISE on failed cast 

Alternatively, you can just call `encodeSerializableValue` with ByteArraySerializer if you need Json support for ProtoUnknownFieldHolder. But I'm not sure it is needed.

2026-08-17 15:38 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +internal fun readRawFieldBytes(decoder: ProtobufDecoder, currentTag: ProtoDesc): ByteArray {
This whole method can be moved inside `decodeRawElement(protoId: Int)` since `decoder` already knows `currentType`

2026-08-17 16:13 UTC, xiaozhikang0916 commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +internal fun readRawFieldBytes(compositeDecoder: CompositeDecoder): ByteArray {
`this` in the lambda of `Decoder.decodeStructure` has type in `CompositeDecoder`, which is not smartcasted to `ProtobufDecoder`. Do you suggest accessing `decoder` outside of the lambda scope here?

2026-08-18 12:36 UTC, sandwwraith commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +internal fun readRawFieldBytes(compositeDecoder: CompositeDecoder): ByteArray {
Hm, indeed. You can access `currentTag` anyway, so you can drop `internal fun readRawFieldBytes(compositeDecoder: CompositeDecoder)` completely, leaving only `readRawFieldBytes(decoder: ProtobufDecoder, currentTag: ProtoDesc)`.

Or you can edit ProtobufDecoder to narrow the return type on overload: `override fun beginStructure(descriptor: SerialDescriptor): ProtobufDecoder`. You'll have to inline decodeStructure lambda though.

2026-08-18 13:04 UTC, xiaozhikang0916 commented on formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/ProtoUnknownFieldHolderSerializer.kt
> +internal fun readRawFieldBytes(compositeDecoder: CompositeDecoder): ByteArray {
Yeah, `internal fun readRawFieldBytes(compositeDecoder: CompositeDecoder)` and some unnecessary type cast have been removed in my last commit.

2026-08-21 15:10 UTC, sandwwraith approved these changes
Thanks a lot for this huge missing piece in protobuf support!

2026-08-21 15:11 UTC, merged

2026-08-25 09:13 UTC, xiaozhikang0916 commented
What should I do to progress the related PR in Kotlin https://github.com/JetBrains/kotlin/pull/5755?

2026-08-26 10:55 UTC, sandwwraith commented
@shanshin will take it from there.